import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  Circle,
  CircleHelp,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  Compass,
  Droplets,
  Footprints,
  Image,
  LocateFixed,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  Maximize,
  Minus,
  Moon,
  Mountain,
  MountainSnow,
  Navigation,
  Pause,
  Play,
  Plus,
  RotateCw,
  Search,
  Settings,
  SlidersHorizontal,
  Snowflake,
  Star,
  Sun,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Wind,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { CSSProperties } from 'react';

/** Lucide-Icons unter ihrem Namen — erlaubt den 1:1-Port der Prototyp-JSX
 *  (`<Icon name="Mountain" />`). Fehlt ein Name, rendert nichts. */
const ICONS: Record<string, LucideIcon> = {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  Circle,
  CircleHelp,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  CloudSun,
  Compass,
  Droplets,
  Footprints,
  Image,
  LocateFixed,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  Maximize,
  Minus,
  Moon,
  Mountain,
  MountainSnow,
  Navigation,
  Pause,
  Play,
  Plus,
  RotateCw,
  Search,
  Settings,
  SlidersHorizontal,
  Snowflake,
  Star,
  Sun,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Wind,
  X,
};

export function Icon({
  name,
  size = 20,
  stroke = 1.75,
  className,
  style,
}: {
  name: string;
  size?: number;
  stroke?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} strokeWidth={stroke} className={className} style={style} aria-hidden />;
}
